K8 spsmdb 794 psmdb release prod
Percona-Lab/percona-version-service pull request #123
Opened 2023-03-08 06:58 UTC by nmarukovich

2023-03-08 07:05 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2023-03-08 07:26 UTC, tplavcic requested changes

2023-03-08 07:26 UTC, tplavcic commented on sources/operator.1.14.0.psmdb-operator.json
> +            "image_hash": "sha256:22152eb2188b1d1fd6100daca41f460b7353acb1be9df783299f680465dd999e",
Image was rebuild so this needs updating.

2023-03-08 07:43 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2023-03-08 10:25 UTC, tplavcic approved these changes

2023-03-13 13:31 UTC, hors approved these changes

2023-03-13 13:34 UTC, merged