K8SPG-315 Incorporate pg v2 images
Percona-Lab/percona-version-service pull request #142
Opened 2023-04-04 10:35 UTC by cap1984

PG v2 is not the latest operator version available due to version branching, so, no reflection inside latest operator section tests

2023-04-04 10:43 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

2023-04-04 11:32 UTC, hors requested changes

2023-04-04 11:32 UTC, hors commented on sources/operator.2.0.0.pg-operator.dep.json
> +     "14.6":{
we have PG 15 for v2

2023-04-04 11:32 UTC, hors commented on sources/operator.2.0.0.pg-operator.dep.json
> +  "pgbackrest_repo":{
we do not have pgbackrest image

2023-04-04 11:32 UTC, hors commented on sources/operator.2.0.0.pg-operator.json
> +          "14.6": {
please add 15.2

2023-04-04 11:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

2023-04-04 12:44 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

2023-04-04 13:06 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

2023-04-04 13:10 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

2023-04-04 13:22 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | failed |

2023-04-04 13:26 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2023-04-05 09:54 UTC, egegunes approved these changes

2023-04-10 11:58 UTC, hors approved these changes

2023-04-20 08:55 UTC, merged