Ignore prerelease in semver
Percona-Lab/percona-version-service pull request #20
Opened 2020-10-02 12:28 UTC by blez

2020-10-02 12:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2020-10-02 13:05 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2020-10-02 13:05 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2020-10-04 17:34 UTC, tplavcic approved these changes

2020-10-05 10:30 UTC, delgod requested changes

2020-10-05 10:30 UTC, delgod commented on server/filters.go
> +			if s.Equal(c) || (s.Major() < c.Major() && s.Minor() < c.Minor() && s.Patch() < c.Patch()) {
maybe will it be better?
```suggestion
			if s.Major() = c.Major() && s.Minor() = c.Minor() && s.Patch() = c.Patch() {
```

2020-10-05 13:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2020-10-05 13:38 UTC, delgod approved these changes

2020-10-05 13:39 UTC, merged