K8SPSMDB-1098: Add PSMDB operator 1.17.0
Percona-Lab/percona-version-service pull request #271
Opened 2024-08-07 19:59 UTC by jvpasinatto

2024-08-07 20:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2024-08-08 11:04 UTC, hors requested changes

2024-08-08 12:21 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2024-08-08 12:21 UTC, eleo007 approved these changes

2024-08-08 12:31 UTC, hors approved these changes

2024-08-08 12:37 UTC, merged

2024-08-08 12:38 UTC, ptankov approved these changes