K8SPG-159 remove old mongo-driver versions
Percona-Lab/percona-version-service pull request #62
Opened 2022-01-19 12:26 UTC by nonemax

2022-01-19 12:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2022-01-20 12:40 UTC, hors requested changes

2022-01-20 12:40 UTC, hors commented on go.mod
> +go 1.15
I think we need to use 1.17

2022-01-20 12:40 UTC, delgod submitted a review, later dismissed

2022-01-21 12:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2022-01-31 07:24 UTC, egegunes approved these changes

2022-01-31 07:55 UTC, hors approved these changes

2022-01-31 19:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| api-tests | passed |

2022-01-31 19:45 UTC, merged