New flow documentation
Percona-Lab/percona-version-service pull request #78
Opened 2022-06-08 15:15 UTC by BupycHuk

2022-06-08 15:19 UTC, nmarukovich commented on README.md
> +Once your PR is merged, our CI will automatically publish these changes to corresponding environment.
Does it work for production already?

2022-06-08 15:35 UTC, BupycHuk commented on README.md
> +Once your PR is merged, our CI will automatically publish these changes to corresponding environment.
Not yet, but I made changes in advance.

2022-06-08 16:27 UTC, nmarukovich approved these changes

2022-06-08 16:31 UTC, hors approved these changes

2022-06-09 07:49 UTC, tplavcic requested changes
My only concern is if we have two completely separate branches main | production and start cherry-picking can it happen that these branches will somehow diverge over time if we are not careful?

2022-06-09 09:50 UTC, BupycHuk commented
@tplavcic yes, that's possible, but we always can compare development and production branches to fix these problems.

2022-07-15 14:41 UTC, merged